# elasticsearch for installing
From elasticsearch:5.6.8

#安装ik分词
RUN  ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.8/elasticsearch-analysis-ik-5.6.8.zip

EXPOSE 9200
